import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NavContactDetail from "@/components/NavContactDetail";
import Packages from "@/components/Packages";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen  flex flex-col justify-between`}
      >
        <NavContactDetail />
        <Navbar />
        <div className="  flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
